print ('Ini program pertama saya')
print ('Nama saya anggun')
print ('Alamat saya dari Muntok Bangka Barat')
print ('Hobi saya menyanyi')
print ('Saya berasal dari sekolah SMA Negeri 1 Muntok')
print ('Saya lahir pada tanggal 08-Juni-2005')