# -*- coding: utf-8 -*-
"""python_operator_Anggun

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15s4j3t7eaC2kMawZAGKBGIiNya1bARCH
"""

#penugasan pertama
a = 10

print('a = 10 -> ', a)

print (' prime a=10-> ', a)

a, b, c = 44, 50, 12

print (a, '>', b, '=', a > b)
print (a, '<', b, '=', a < b)
print (a, '==', b, '=', a == b)
print (a, '!=', b, '=', a != b)
print (a, '>=', b, '=', a >= b)
print (a, '<=', b, '=', a <= b)

print (a, '!=', b, '==', c, '=', a != b == c)

print (a, '!=', b, '<', c, '=', a != b < a)

a = 7

print('a = 7 -> ', a)

a += 7

print('a += 7 -> ', a)

a -= 11

print('a -= 11 -> ', a)

a *=33
print('a *= 33 -> ', a)

a /=59
print('a /= 59 -> ', a)

# karena a jadi float, kita ubah lagi menjadi integer
a = int(a)

a %= 88
print('a %= 88 ->', a)

a //= 35
print('a //= 35 ->', a)

a **= 22
print('a **= 22 ->', a)

a = 8
b = 3
nama_a = 'budi'
nama_b = 'budi'

print('a is b:', a is b)

print('a is not b:', a is not b) # output False print('a is not b:', a is not b)

print('nama_a is nama_b:', nama_a is nama_b)

print(True and True)

print (1+2==3 and True)

print (' . ---'  )

print (False or 1 > 5 )

print(False or 5 > 7 )

print(False or 5 > 2 )

print ('----')

print(not(1 > 5))

print(not(11 > 5))

print(not(4 < 5))

print(not(1 < 5))

kerajaan = 'rusdi_empire'
list_kerajaan = ['jawa', 'ngawi','bogor', 'jateng']

print("apakah 'ngawi' ada di variabel list_kerajaan?", 'b' in kerajaan)

>>> id('merah')

>>> id('merah')

>>> id ('11')

>>> id ('11')

>>> id ('11')

>>> id ('661')

>>> id ('jawa')

>>> id ('jawa')

>>> id ('jateng')

>>> id ('jateng 1')

>>> id ('jateng 1')

